#!/usr/bin/env python
#
# Software License Agreement (BSD)
#
# @author    Mike Purvis <mpurvis@clearpathrobotics.com>
# @author    Chris Iverach-Brereton <civerachb@clearpathrobotics.com>
# @copyright (c) 2014, Clearpath Robotics, Inc., All rights reserved.
# @usage     download_spinnaker {arch} {dir} {os-code-name}
#            e.g. download_spinnaker x86_64 /path/to/somewhere xenial
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
# * Redistributions of source code must retain the above copyright notice, this list of conditions and the
#   following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
#   following disclaimer in the documentation and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or
#   promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import cookielib
import cStringIO
import logging
import shutil
import subprocess
import sys
import tarfile
import urllib
import urllib2
import os
import glob

logging.basicConfig(level=logging.INFO)

URL_TEMPLATE = URL_TEMPLATES = {
    'deb': 'https://polybox.ethz.ch/index.php/s/07EyM7FVhnRDkvH/download',
    'src': None         # if we ever have non-deb archives that require manual extraction, those package URLS will go here.
}

ARCHS = {
    'i386': {
        'linux_arch': 'i386',
        'current': '16.04',
        'type': 'deb',
        'folder_name': 'spinnaker-2.2.0.48-i386',
        'shared_library': 'opt/spinnaker/lib/libSpinnaker.so.2.2.0.48',
        'debs': [
            'libspinnaker_2.2.0.48_i386.deb',
            'libspinnaker-dev_2.2.0.48_i386.deb',
            'libspinnaker-c_2.2.0.48_i386.deb',
            'libspinnaker-c-dev_2.2.0.48_i386.deb',
            'libspinvideo_2.2.0.48_i386.deb',
            'libspinvideo-dev_2.2.0.48_i386.deb',
            'libspinvideo-c_2.2.0.48_i386.deb',
            'libspinvideo-c-dev_2.2.0.48_i386.deb',
            'spinnaker_2.2.0.48_i386.deb',
            'spinnaker-doc_2.2.0.48_i386.deb',
            'spinupdate_2.2.0.48_i386.deb',
            'spinupdate-dev_2.2.0.48_i386.deb',
            'spinview-qt_2.2.0.48_i386.deb',
            'spinview-qt-dev_2.2.0.48_i386-dev.deb'
        ]
    },
    'x86_64': {
        'linux_arch': 'amd64',
        'current': '16.04',
        'future': '18.04',
        'type': 'deb',
        'folder_name': 'spinnaker-2.2.0.48-amd64',
        'shared_library': 'opt/spinnaker/lib/libSpinnaker.so.2.2.0.48',
        'debs': [
            'libspinnaker_2.2.0.48_amd64.deb',
            'libspinnaker-dev_2.2.0.48_amd64.deb',
            'libspinnaker-c_2.2.0.48_amd64.deb',
            'libspinnaker-c-dev_2.2.0.48_amd64.deb',
            'libspinvideo_2.2.0.48_amd64.deb',
            'libspinvideo-dev_2.2.0.48_amd64.deb',
            'libspinvideo-c_2.2.0.48_amd64.deb',
            'libspinvideo-c-dev_2.2.0.48_amd64.deb',
            'spinnaker_2.2.0.48_amd64.deb',
            'spinnaker-doc_2.2.0.48_amd64.deb',
            'spinupdate_2.2.0.48_amd64.deb',
            'spinupdate-dev_2.2.0.48_amd64.deb',
            'spinview-qt_2.2.0.48_amd64.deb',
            'spinview-qt-dev_2.2.0.48_amd64.deb'
        ]
    },
    'armv7': {
        'linux_arch': 'armhf',
        'current': '16.04',
        'type': 'deb',
        'shared_library': 'opt/spinnaker/lib/libSpinnaker.so.2.2.0.48',
        'folder_name': 'spinnaker-2.2.0.48_armhf',
        'debs': [
            'libspinnaker_2.2.0.48_armhf.deb',
            'libspinnaker-dev_2.2.0.48_armhf.deb',
            'libspinnaker-c_2.2.0.48_armhf.deb',
            'libspinnaker-c-dev_2.2.0.48_armhf.deb',
            'libspinvideo_2.2.0.48_armhf.deb',
            'libspinvideo-dev_2.2.0.48_armhf.deb',
            'libspinvideo-c_2.2.0.48_armhf.deb',
            'libspinvideo-c-dev_2.2.0.48_armhf.deb',
            'spinnaker_2.2.0.48_armhf.deb',
            'spinnaker-doc_2.2.0.48_armhf.deb',
            'spinupdate_2.2.0.48_armhf.deb',
            'spinupdate-dev_2.2.0.48_armhf.deb',
            'spinview-qt_2.2.0.48_armhf.deb',
            'spinview-qt-dev_2.2.0.48_armhf.deb'
        ]
    },
    'armv8':  {
        'linux_arch': 'armh64',
        'current': '16.04',
        'future': '18.04',
        'type': 'deb',
        'shared_library': 'opt/spinnaker/lib/libSpinnaker.so.2.2.0.48',
        'folder_name': 'spinnaker-2.2.0.48_arm64',
        'debs': [
            'libspinnaker_2.2.0.48_arm64.deb',
            'libspinnaker-dev_2.2.0.48_arm64.deb',
            'libspinnaker-c_2.2.0.48_arm64.deb',
            'libspinnaker-c-dev_2.2.0.48_arm64.deb',
            'libspinvideo_2.2.0.48_arm64.deb',
            'libspinvideo-dev_2.2.0.48_arm64.deb',
            'libspinvideo-c_2.2.0.48_arm64.deb',
            'libspinvideo-c-dev_2.2.0.48_arm64.deb',
            'spinnaker_2.2.0.48_arm64.deb',
            'spinnaker-doc_2.2.0.48_arm64.deb',
            'spinupdate_2.2.0.48_arm64.deb',
            'spinupdate-dev_2.2.0.48_arm64.deb',
            'spinview-qt_2.2.0.48_arm64.deb',
            'spinview-qt-dev_2.2.0.48_arm64.deb'
        ]
    }
}


OS_LIBRARY_VERSION = {
  'jessie': 'current',
  'xenial': 'current',
  'bionic': 'future'
}

arch = sys.argv[1]
destination_folder = sys.argv[2]
os_code_name = sys.argv[3]

os_version = OS_LIBRARY_VERSION[os_code_name]
archive_url = URL_TEMPLATES[ARCHS[arch]['type']].format(
    arch=ARCHS[arch]['linux_arch'],
    version=ARCHS[arch][os_version])
folder_name = ARCHS[arch]['folder_name']
shared_library = ARCHS[arch]['shared_library']


logging.info("CPU architecture is %s", arch)
logging.info("OS code name is %s", os_code_name)
logging.info("Destination folder is %s", destination_folder)

if not os.path.exists(os.path.join(os.getcwd(), "opt/spinnaker/lib/")):
    if not os.path.exists(os.path.join(os.getcwd(), folder_name)):
        cj = cookielib.CookieJar()
        opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cj))
        opener.addheaders = [
            ('User-agent', 'Mozilla/5.0'),
            ('Referer', 'https://www.ptgrey.com')]

        logging.info("Downloading SDK archive from {0}...".format(archive_url))
        resp = opener.open(archive_url)

        logging.info("Unpacking tarball.")
        with tarfile.open(mode="r:gz", fileobj=cStringIO.StringIO(resp.read())) as tar:
            tar.extractall()

    logging.info("Unpacking debs.")
    debs = glob.glob(os.path.join(os.getcwd(), folder_name, "*spinnaker*.deb"))
    unpack_dir = os.path.join(os.getcwd())
    if not os.path.exists(unpack_dir):
        os.makedirs(unpack_dir)
    for deb in debs:
        logging.info('Extracting {0}'.format(deb))
        subprocess.call(['dpkg', '--extract', deb, unpack_dir])
